### ISSUE TITLE
Attempt to upload 2MB file fails silently

### ISSUE THREAD

**Issue by stevenwhiz** [CodePadSite/codepad-issues#53] opened 2021-09-16 22:26 UTC
Attempting to upload 2MB file or greater fails silently.  It's not clear what the file size limit is.

1. The file size limit should be increased, perhaps to 20 MB.
2. When it exceeds the file limit size, it should report an error.

**Comment by Bongs237** [comment] 2021-09-16 23:43
Duplicate of #49

**Closed by Bongs237** 2021-09-16 23:43 UTC
Labels: bug, P3
